[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/feed.xml"
  to = "/.netlify/functions/feed"
  status = 200

[[redirects]]
  from = "/mailchimp-news"
  to = "/.netlify/functions/mailchimp-news"
  status = 200

[[redirects]]
  from = "/blueprint.html"
  to = "/bcoe-contractor-development-institute.html"
  status = 301
